Add and remove tasks from list
sadaf-Daneshgar/To-Do-list pull request #2
Opened 2023-06-15 13:55 UTC by sadaf-Daneshgar

**New Feature**

- Added a new JavaScript file for the new functionality.
- Implement a function for adding a new task
- Implement a function for deleting a tasks
- Implement a function for editing task descriptions
- Add functionality for save to to list into local storage

**Thank you!**

2023-06-15 14:34 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @sadaf-Daneshgar 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-15 14:34 UTC, tresorsawasawa commented on src/addremove.js
> +/* eslint-disable no-use-before-define */
- [ ] For best practices and clean code reasons, kindly ensure that you fix your linters error instead of disabling them. I suggest you apply this approach every where you disable them from your code base.

2023-06-15 14:34 UTC, tresorsawasawa commented on src/addremove.js
> +
- [ ] `README.md` file: To make your documentation looks professional, I think it would be better if you fix the `broken image` at the top of your README and **update the name of your project.** Right now your application is named `Awesome Book` instead of `To Do list`. I can suggest you completely remove that image,  Optionally, you can replace it with your own logo if you have one.
![Screenshot from 2023-06-15 16-16-46](https://github.com/sadaf-Daneshgar/To-Do-list/assets/83042742/5eedb8f1-7755-46ea-abda-62fb8a687155)

2023-06-15 14:34 UTC, tresorsawasawa commented on src/addremove.js
> +
- [ ] As required for the project, kindly ensure that after deleting a task should update all remaining items' `indexes`, so they represent the current list order and are unique. Right now, a user deletes a task from the list, it remains with the same `index number`, and if added new one, you will have duplicate tasks with the same `index number`. You can see the issue you have in below image.
![Screenshot from 2023-06-15 16-29-51](https://github.com/sadaf-Daneshgar/To-Do-list/assets/83042742/9dbcad11-8cad-446a-9f53-63244c4a09d6)

2023-06-15 16:15 UTC, Shisui6 requested changes
Hi @sadaf-Daneshgar, 

# Requires Changes 🍀
Great work on making the changes requested by a previous reviewer 👍
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet🪲.


 ## Highlights 🎯
 - Descriptive PR title and summary ✅
 - Follows Github flow ✅
 - Good commit messages ✅

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 🪶

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will really improve your application._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-15 16:15 UTC, Shisui6 commented on src/addremove.js
> +    // eslint-disable-next-line no-use-before-define
As suggested by the previous reviewer, please remove **all** lines which disable linter checks in your project and try to solve the linter errors yourself. The linter checks are essential to help us become better developers by enforcing best coding practices.

2023-06-16 16:54 UTC, roshan-bajgain requested changes
Hi @sadaf-Daneshgar, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- GitHub flow is followed. ✔️
- Good job on implementing some changes ✔️ 


 ## Required Changes ♻️
- [ ] After you complete this you can ask for additional review. [Link](https://airtable.com/shrQAqnBwek5a0O0s)
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-16 16:54 UTC, roshan-bajgain commented on src/addremove.js
> +  taskItem.appendChild(deleteButton);
- [ ] As requested by the first reviewer your index value is not updating after deleting the items. When I delete a task it should update all remaining items' indexes. But the index is not updating after removing the items. Just you need to update the local storage after deleting the items then you are good to go.
### Error
![his](https://github.com/sadaf-Daneshgar/To-Do-list/assets/81727988/0969761f-6c3f-4d0b-9b53-5f50dafb8074)

2023-06-16 17:03 UTC, sadaf-Daneshgar commented on src/addremove.js
> +  taskItem.appendChild(deleteButton);
Hello @roshan-bajgain 

but can you see this problem is not show for me
I add the task 3 and delete but it updated 
![image](https://github.com/sadaf-Daneshgar/To-Do-list/assets/124706141/9578239e-f49d-41a5-9d77-d0da83728466)

2023-06-16 17:52 UTC, roshan-bajgain commented on src/addremove.js
> +  taskItem.appendChild(deleteButton);
Hello @sadaf-Daneshgar, I double check it and still your local storage is not updating after the item is removed. After deleting the list you should update the local storage so that it shows the current index.

2023-06-16 18:21 UTC, roshan-bajgain commented on src/addremove.js
> +  taskItem.appendChild(deleteButton);
Hello @sadaf-Daneshgar,  To address this issue, you can modify the deleteTask function as 
`const deleteTask = (task) => {`
  `const index = tasks.indexOf(task);`
 ` if (index > -1) {`
    `tasks.splice(index, 1);`
   ` updateTaskIndexes(); // Update the indexes after deleting a task`
    `saveTasks();`
  }
};`

In the deleteTask function, after removing the task from the array, the updateTaskIndexes function is called to ensure the indexes are recalculated correctly.

2023-06-17 07:09 UTC, addod19 approved these changes
### Hi @sadaf-Daneshgar, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### Highlights
- [ ] Nice job addressing the comment about indexes updates, now t works as expected :rocket: 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-17 07:09 UTC, addod19 commented on README.md
### Optional
- [ ] In the MIT license file, it would be better if we put our name there instead of the placeholder text as seen n the screenshot below
![Screenshot from 2023-06-17 07-03-13](https://github.com/sadaf-Daneshgar/To-Do-list/assets/46388113/14178156-27f1-45bf-a408-af35bba235e3)

2023-06-17 12:48 UTC, sadaf-Daneshgar commented
Hello dear code reviewer sorry I want to mention one thing that used this pull request for my day 3 project also because I added the actions on this pull request but I will not repeat this again I will create new pull request for every project just now please accept this because it is my extra review and also the deadline also finish but I promise I will not repeat.
Thank you.

2023-06-17 13:00 UTC, ridwanediallo approved these changes
# STATUS: APPROVED 🟢
## Hi @sadaf-Daneshgar , 
![Congratulations!GIF](https://user-images.githubusercontent.com/55918904/191301390-43d62dfa-bfdc-49c5-943b-4d72f4ea5bb8.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used GitHub flow correctly. ✔
- Well done implementing the change suggested by the reviewer [roshan-bajgain](https://github.com/roshan-bajgain)
- You successfully completed all the requirements.  🎉 🎉 🎉 ✔

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-17 13:01 UTC, merged